import { motion } from 'framer-motion';
import { useEffect, useRef } from 'react';

export function Scene5() {
  const audioRef = useRef<HTMLAudioElement>(null);

  useEffect(() => {
    // Attempt to autoplay the cinematic audio generated by the app
    if (audioRef.current) {
      audioRef.current.play().catch(e => console.warn("Audio autoplay blocked:", e));
    }
  }, []);

  return (
    <motion.div
      className="absolute inset-0 bg-[#eee7dc] flex items-center justify-center overflow-hidden"
      initial={{ scale: 1.1, opacity: 0 }}
      animate={{ scale: 1, opacity: 1 }}
      exit={{ y: "-100%" }}
      transition={{ duration: 1.5, ease: [0.76, 0, 0.24, 1] }}
    >
      {/* Cinematic audio file copied from the workspace */}
      <audio 
        ref={audioRef}
        src={`${import.meta.env.BASE_URL}audio/clip-script-brief-concept-format-trust.wav`}
        className="hidden"
      />

      {/* Audio Waveform Background */}
      <div className="absolute inset-0 flex items-center justify-center opacity-15 gap-[0.5vw]">
        {[...Array(50)].map((_, i) => (
          <motion.div
            key={i}
            className="w-[1.2vw] bg-[#b34b36] rounded-full mix-blend-multiply"
            animate={{
              height: ["2vw", `${Math.random() * 25 + 5}vw`, "2vw"]
            }}
            transition={{
              duration: Math.random() * 1.5 + 0.5,
              repeat: Infinity,
              ease: "easeInOut",
              delay: Math.random() * 2
            }}
          />
        ))}
      </div>

      <div className="relative z-10 w-[80vw] text-center">
        <motion.p
          className="font-mono text-[#eee7dc] bg-[#b34b36] px-[1.5vw] py-[0.5vw] inline-block text-[1.2vw] uppercase tracking-widest mb-[2vw] font-bold shadow-lg"
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 1 }}
        >
          Human Conversation → Audio Now
        </motion.p>
        
        <motion.h2
          className="font-serif text-[#201b19] text-[4vw] leading-[1.1] max-w-[70vw] mx-auto drop-shadow-sm"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 2, duration: 1 }}
        >
          Direct @google/genai performs structured conversational script generation and multi-speaker TTS.
        </motion.h2>
        
        <motion.p
          className="font-serif text-[#5f554e] text-[1.8vw] mt-[1vw] max-w-[60vw] mx-auto italic"
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 3, duration: 1 }}
        >
          Live trending talk becomes an immediate, natural-sounding two-host podcast clip.
        </motion.p>

        <div className="flex justify-center gap-[4vw] mt-[4vw]">
          <motion.div
            className="bg-[#f0e8de]/95 backdrop-blur-sm border-2 border-[#c7b9aa] p-[3vw] w-[35vw] text-left shadow-2xl"
            initial={{ opacity: 0, rotateY: 90 }}
            animate={{ opacity: 1, rotateY: 0 }}
            transition={{ delay: 4, duration: 1.2, ease: "easeOut" }}
          >
            <p className="font-mono text-[#b34b36] text-[1vw] uppercase tracking-widest mb-[0.5vw] font-bold">Voice 01 / Kore</p>
            <h3 className="font-serif text-[#201b19] text-[2.5vw] font-bold">FRONT ROW</h3>
            <p className="font-serif text-[#5f554e] text-[1.5vw] mt-[1.5vw] leading-relaxed italic">
              "We're seeing a massive shift in how these stories break. It's not press releases anymore, it's open signal."
            </p>
            <div className="w-full h-[3px] bg-[#c7b9aa] mt-[2vw] relative overflow-hidden">
              <motion.div 
                className="absolute top-0 left-0 bottom-0 bg-[#b34b36]"
                initial={{ width: 0 }}
                animate={{ width: "100%" }}
                transition={{ delay: 5.5, duration: 8, ease: "linear" }}
              />
            </div>
          </motion.div>

          <motion.div
            className="bg-[#f0e8de]/95 backdrop-blur-sm border-2 border-[#c7b9aa] p-[3vw] w-[35vw] text-left shadow-2xl"
            initial={{ opacity: 0, rotateY: -90 }}
            animate={{ opacity: 1, rotateY: 0 }}
            transition={{ delay: 4.5, duration: 1.2, ease: "easeOut" }}
          >
            <p className="font-mono text-[#365f67] text-[1vw] uppercase tracking-widest mb-[0.5vw] font-bold">Voice 02 / Puck</p>
            <h3 className="font-serif text-[#201b19] text-[2.5vw] font-bold">BACKSTAGE</h3>
            <p className="font-serif text-[#5f554e] text-[1.5vw] mt-[1.5vw] leading-relaxed italic">
              "Exactly. And looking at the data, the engagement velocity completely bypassed traditional channels."
            </p>
            <div className="w-full h-[3px] bg-[#c7b9aa] mt-[2vw] relative overflow-hidden">
              <motion.div 
                className="absolute top-0 left-0 bottom-0 bg-[#365f67]"
                initial={{ width: 0 }}
                animate={{ width: "100%" }}
                transition={{ delay: 9.5, duration: 6, ease: "linear" }}
              />
            </div>
          </motion.div>
        </div>
      </div>
    </motion.div>
  );
}
